# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Arnob Paul
description: > # this means to ignore newlines until "baseurl:"
  Material theme based on <a href="https://materializecss.com" target="_blank" onclick="trackOutboundLink('https://materializecss.com')">Materialize.css</a> for <a href="https://jekyllrb.com" target="_blank" onclick="trackOutboundLink('https://jekyllrb.com')">Jekyll</a> sites

baseurl: ""
url: ""

permalink: /:year/:month/:day/:title
include: ['_pages']
relative_permalinks: false
paginate_path: /page:num
paginate: 5

defaults:
  -
    scope:
      path: "_pages"
    values:
      layout: page
      permalink: /:basename

# My GitHub configurations
repository: arnobpl/arnobpl\.github\.io
github_profile: "https://github.com/arnobpl"

# My specific configurations
user: "Arnob Paul"
user_email: "arnobpl@gmail.com"
cv_google_fileId: "0BzP145FbccCFSlVrVFhoYWNqWWc"
google_tracking_id: "G-E26F2GYGSC"
google_site_verification: "SvHMGI2isB6HNwXZlY13M7vdEPpfj9KJOiPExVefDC0"
# disqus_shortname: "arnobpl"

# Jekyll Scholar settings
scholar:
  style: apa
  source: ./_bib
  bibliography: publication.bib

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
  - jekyll-scholar
exclude:
  - Gemfile
  - Gemfile.lock
sassc:
  style: compressed
future: true