# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Arnob Paul
description: > # this means to ignore newlines until "baseurl:"
  Material theme based on <a href="https://materializecss.com">Materialize.css</a> for <a href="https://jekyllrb.com">Jekyll</a> sites

baseurl: ""
url: ""

permalink: /:year/:month/:day/:title
include: ['_pages']
relative_permalinks: false
paginate_path: /page:num
paginate: 5

defaults:
  -
    scope:
      path: "_pages"
    values:
      permalink: /:basename

repository: arnobpl/arnobpl\.github\.io

# MatJek specific configurations
github_profile: "https://github.com/arnobpl"
user: "Arnob Paul"
user_email: "arnobpl@gmail.com"
cv_google_fileId: "1zn98ZuQdSLGJnwJkK0MvoKVDxa15OCTO"
google_tracking_id: "UA-40979540-3"
google_site_verification: "UA-40979540-3"
# disqus_shortname: "matjek"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  style: compressed
future: true